<?php

require '../vendor/autoload.php';
$count = 1;
while($count <= 100)
{
    $myfile = fopen("luck/luck_{$count}.txt", "r") or die("Unable to open file!");
	$text = fread($myfile,filesize("luck/luck_{$count}.txt"));
	fclose($myfile);
	$transform = new Text2pic\Transform('Generated by Madao', 'C:\wamp64\www\text2pic\test\luck_img', '/');
	$result = $transform->generate($text);
	if($result['code']==200){
		print_r($result);
		$filename = str_replace("/","",$result['data']['url']);
		rename("luck_img/{$filename}", "luck_img/luck_{$count}.jpg");
		echo $filename;
	}else{
		echo $result['message'];
	};
    $count++;
}

?>